- id: beman-tidy
  name: "beman-tidy: The Codebase Bemanification Tool"
  entry: bash -c 'cd tools/beman-tidy && uv run beman-tidy "$@"' --
  language: system
  pass_filenames: false
  always_run: true
  args: [".", "--verbose"]
