#ifndef INCLUDED_BEMAN_MY_LIB_DETAIL_SOME_DEPENDENCY_H
#define INCLUDED_BEMAN_MY_LIB_DETAIL_SOME_DEPENDENCY_H

// Missing namespace
struct some_dependency {};

#endif // INCLUDED_BEMAN_MY_LIB_DETAIL_SOME_DEPENDENCY_H
